# Generated by Django 4.0.4 on 2022-05-31 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='Watchlist_item',
        ),
    ]
