# Generated by Django 4.0.4 on 2022-05-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_rename_favorites_favorite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='watchlist_item',
            old_name='user_id',
            new_name='user',
        ),
    ]
