# Generated by Django 4.0.4 on 2022-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_rename_user_id_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist_item',
            name='user_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
