# Generated by Django 4.0.4 on 2022-06-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0007_tierlist_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierlist_rating',
            name='favorite',
        ),
        migrations.AddField(
            model_name='favorite',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animes.tierlist_rating'),
        ),
    ]
