# Generated by Django 4.0.4 on 2022-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0010_remove_favorite_added_at_favorite_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist_item',
            name='episodes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
